/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *btnopen;
  GtkWidget *btnsetcountermode;
  GtkWidget *btnstart;
  GtkWidget *btnstop;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *btnreaddata;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("vscopedevice demo"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 120, 136);
  gtk_widget_set_size_request (entry1, 160, 27);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 120, 168);
  gtk_widget_set_size_request (entry2, 160, 27);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 120, 200);
  gtk_widget_set_size_request (entry3, 160, 27);

  btnopen = gtk_button_new_with_mnemonic (_("open VScope"));
  gtk_widget_show (btnopen);
  gtk_fixed_put (GTK_FIXED (fixed1), btnopen, 8, 8);
  gtk_widget_set_size_request (btnopen, 120, 24);

  btnsetcountermode = gtk_button_new_with_mnemonic (_("Set Counter Mode"));
  gtk_widget_show (btnsetcountermode);
  gtk_fixed_put (GTK_FIXED (fixed1), btnsetcountermode, 8, 40);
  gtk_widget_set_size_request (btnsetcountermode, 144, 24);

  btnstart = gtk_button_new_with_mnemonic (_("Start VScope"));
  gtk_widget_show (btnstart);
  gtk_fixed_put (GTK_FIXED (fixed1), btnstart, 8, 72);
  gtk_widget_set_size_request (btnstart, 96, 24);

  btnstop = gtk_button_new_with_mnemonic (_("Stop VScope"));
  gtk_widget_show (btnstop);
  gtk_fixed_put (GTK_FIXED (fixed1), btnstop, 8, 104);
  gtk_widget_set_size_request (btnstop, 96, 24);

  button5 = gtk_button_new_with_mnemonic (_("FIFO Load"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 8, 136);
  gtk_widget_set_size_request (button5, 104, 24);

  button6 = gtk_button_new_with_mnemonic (_("VScope Mode"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed1), button6, 8, 168);
  gtk_widget_set_size_request (button6, 104, 24);

  button7 = gtk_button_new_with_mnemonic (_("VScope State"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed1), button7, 8, 200);
  gtk_widget_set_size_request (button7, 104, 24);

  btnreaddata = gtk_button_new_with_mnemonic (_("Read Data"));
  gtk_widget_show (btnreaddata);
  gtk_fixed_put (GTK_FIXED (fixed1), btnreaddata, 128, 72);
  gtk_widget_set_size_request (btnreaddata, 80, 24);

  g_signal_connect ((gpointer) btnopen, "clicked",
                    G_CALLBACK (on_btnopen_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnsetcountermode, "clicked",
                    G_CALLBACK (on_btnsetcountermode_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnstart, "clicked",
                    G_CALLBACK (on_btnstart_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnstop, "clicked",
                    G_CALLBACK (on_btnstop_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnreaddata, "clicked",
                    G_CALLBACK (on_btnreaddata_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, btnopen, "btnopen");
  GLADE_HOOKUP_OBJECT (window1, btnsetcountermode, "btnsetcountermode");
  GLADE_HOOKUP_OBJECT (window1, btnstart, "btnstart");
  GLADE_HOOKUP_OBJECT (window1, btnstop, "btnstop");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, btnreaddata, "btnreaddata");

  return window1;
}

